spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springdb
    username: root
    password: root123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false